include (":typing")
include (":core")
include (":commonUI")
include (":python")
include (":learn")
include (":IntelHexFormatReader")
//include (":chat")
include (":app")
rootProject.name = "Saral"
include(":webIDE")
