# Triggers the workflow on merge events but only for the main branch

name: Create New Release 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Create local.properties 
        shell: bash
        run: |
          touch ./local.properties
          echo "⚙️ Creating a new local.properties file"
          echo "sdk.dir=ANDROID_SDK_ROOT" > ./local.properties

      - name: 📦 Build the app
        run: ./gradlew app:assembleDebug
        
      - name: 🧹 Check Lint
        run: ./gradlew app:lint
      
      - name: 🧪 Run tests
        run: ./gradlew app:test

      - name: 🏷️ Extract Version Name
        run: |
          VERSION_NAME=$(python3 -c "import re; print(re.search(r'const val versionName = \"([^\"]+)\"', open('buildSrc/src/main/kotlin/Dependencies.kt').read()).group(1))")
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: 🎁 Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION_NAME }}
          name: Meraki App Release v${{ env.VERSION_NAME }}
          files: app/build/outputs/apk/debug/*-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN || secrets.GITHUB_TOKEN }}
